name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore src/
    - name: Build
      run: dotnet build src/ --no-restore
    - name: Test
      run: dotnet test src/ --no-build --verbosity normal
    
    - name: Build container
      run: docker build --tag someappweb:${{ github.run_number }} src/SomeAppWeb/

  testInContainer:
    runs-on: ubuntu-22.04
    needs: build

    services:
      someappweb:
        image: someappweb:${{ github.run_number }}
    
    steps:
    - name: Curl
      run: curl http://localhost/
