name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
#    - name: Setup .NET
#      uses: actions/setup-dotnet@v3
#      with:
#        dotnet-version: 7.0.x
#    - name: Restore dependencies
#      run: dotnet restore src/
#    - name: Build
#      run: dotnet build src/ --no-restore
#    - name: Test
#      run: dotnet test src/ --no-build --verbosity normal

  testInContainer:
    runs-on: ubuntu-22.04
    needs: build
    
    steps:
    - name: Build container
      run: docker build --tag someappweb:${{ github.run_number }} src/SomeAppWeb/
    - name: Run container
      run: docker run --pull never someappweb:${{ github.run_number }}
    - name: Curl
      run: curl http://localhost/
